# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2016 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2'

services:
  service_base:
    # Overrides default inspirehep config.
    extends:
      file: services.yml
      service: base
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:dbpass123@database:5432/inspirehep
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - CACHE_REDIS_URL=redis://redis:6379/0
      - ACCOUNTS_SESSION_REDIS_URL=redis://redis:6379/2
      - SEARCH_ELASTIC_HOSTS=indexer

  # Services using the inspirehep code.
  web:
    extends:
      service: service_base
    command: gunicorn -b 0.0.0.0:5000 -t 3600 --access-logfile "-" inspirehep.wsgi
    volumes_from:
      - static
    ports:
      - "5000:5000"
    links:
      - database
      - indexer
      - rabbitmq
      - redis
  worker:
    extends:
      service: service_base
    command: celery worker -E -A inspirehep.celery --loglevel=INFO --purge
    volumes_from:
      - static
    links:
      - database
      - indexer
      - rabbitmq
      - redis

  # Services needed for inspirehep to run.
  redis:
    image: redis
  indexer:
    extends:
      file: services.yml
      service: indexer
    ports:
      - "9200:9200"
    volumes:
      - "${DOCKER_DATA}/tmp/inspirehep_elastic/data:/usr/share/elasticsearch/data"
      - "${DOCKER_DATA}/tmp/inspirehep_elastic/log:/usr/share/elasticsearch/log"
  rabbitmq:
    image: rabbitmq
  database:
    extends:
      file: services.yml
      service: database
    volumes:
      - "${DOCKER_DATA}/tmp/inspirehep_db/data:/var/lib/postgresql/data/pgdata"

  # Services useful for monitoring/debugging.
  flower:
    extends:
      service: service_base
    ports:
      - "5555:5555"
    command: flower -A inspirehep.celery --broker=amqp://guest:guest@rabbitmq:5672//
    volumes_from:
      - static
    links:
      - database
      - indexer
      - rabbitmq
      - redis

  # Static volume config for service_base.
  static:
    extends:
      file: services.yml
      service: static
